-- Makes a storyboard reservation idempotent per logical generation request.
--
-- Until now every POST to generate-storyboard minted a fresh storyboard id and reserved fresh
-- credits. Two deliveries of the same intent — a retried request, a client that was killed after the
-- server reserved but before the response arrived, a user tapping again because nothing appeared —
-- each took another credit. The only thing standing in the way was client-side state, which is not
-- where financial correctness belongs.
--
-- The fix is an identity for the *request*, created once by the client when the user intentionally
-- starts one generation, and enforced here. Same request id, same reservation, one deduction. A
-- genuinely new generation carries a new id and reserves separately.

alter table public.entry_storyboards
    add column if not exists generation_request_id uuid;

comment on column public.entry_storyboards.generation_request_id is
    'Client-generated identity of the logical generation request this row was reserved for. Unique
     per user, so a retried request converges on the reservation it already made instead of paying
     for a second one.';

-- The constraint that actually enforces it. Scoped per user rather than globally: request ids are
-- generated by clients, and one client''s id must not be able to collide with — or probe for —
-- another account''s reservation. Partial, so the pre-existing rows that have no request id do not
-- all collide on null.
create unique index if not exists entry_storyboards_generation_request_key
    on public.entry_storyboards (user_id, generation_request_id)
    where generation_request_id is not null;

-- The reservation now takes the request id, and the old seven-argument form is removed rather than
-- left beside it: an overload that reserves without an idempotency key is exactly the thing this
-- migration exists to prevent, and leaving it callable would make the protection optional.
drop function if exists public.reserve_storyboard_generation(uuid, uuid, text, text, text, text, integer);

create or replace function public.reserve_storyboard_generation(
    storyboard_id uuid,
    generation_request_id uuid,
    client_entry_id uuid,
    storage_path text,
    art_style text,
    generation_quality text,
    prompt text,
    credit_cost integer
)
returns public.entry_storyboards
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller uuid := auth.uid();
    reserved public.entry_storyboards%rowtype;
    remaining_balance integer;
begin
    if caller is null then
        raise exception 'not_authenticated';
    end if;

    if generation_request_id is null then
        raise exception 'missing_generation_request_id';
    end if;

    if credit_cost is null or credit_cost <= 0 then
        raise exception 'invalid_credit_cost';
    end if;

    -- The fast path for a retry. Answered before entitlement and before credits, because a request
    -- that has already been paid for is not a new request: a subscription that lapsed between the
    -- first delivery and the retry must not turn an existing reservation into an error, and a
    -- balance that is now empty must not either.
    select * into reserved
    from public.entry_storyboards
    where entry_storyboards.user_id = caller
      and entry_storyboards.generation_request_id = reserve_storyboard_generation.generation_request_id;

    if found then
        return reserved;
    end if;

    if not exists (
        select 1
        from public.entries
        where entries.user_id = caller
          and entries.client_entry_id = reserve_storyboard_generation.client_entry_id
    ) then
        raise exception 'entry_not_found';
    end if;

    -- The authoritative entitlement check, unchanged from 20260817094000 and still ahead of any
    -- spending, so a user without Storytopia+ is turned away having been charged nothing.
    if not public.has_active_storytopia_plus(caller) then
        raise exception 'subscription_required';
    end if;

    -- Two deliveries that arrive close enough together both miss the lookup above. The loser of that
    -- race is caught here: the block is a subtransaction, so the unique index rejecting its insert
    -- rolls back its spend along with it, and it then returns the row the winner committed. One
    -- credit leaves the account no matter how the two requests interleave.
    begin
        remaining_balance := public.spend_generation_credit(reserve_storyboard_generation.credit_cost);

        insert into public.entry_storyboards (
            id,
            user_id,
            client_entry_id,
            generation_request_id,
            storage_path,
            art_style,
            generation_quality,
            panel_layout,
            prompt,
            is_primary,
            generation_status,
            reserved_credits
        )
        values (
            reserve_storyboard_generation.storyboard_id,
            caller,
            reserve_storyboard_generation.client_entry_id,
            reserve_storyboard_generation.generation_request_id,
            reserve_storyboard_generation.storage_path,
            reserve_storyboard_generation.art_style,
            reserve_storyboard_generation.generation_quality,
            null,
            reserve_storyboard_generation.prompt,
            false,
            'pending',
            reserve_storyboard_generation.credit_cost
        )
        returning * into reserved;

        insert into public.credit_ledger (user_id, delta, reason, source_id, balance_after)
        values (
            caller,
            -reserve_storyboard_generation.credit_cost,
            'storyboard_reservation',
            reserve_storyboard_generation.storyboard_id::text,
            remaining_balance
        );
    exception
        when unique_violation then
            select * into reserved
            from public.entry_storyboards
            where entry_storyboards.user_id = caller
              and entry_storyboards.generation_request_id
                  = reserve_storyboard_generation.generation_request_id;

            -- A unique violation that is not this request's own reservation is a real error and is
            -- allowed to propagate rather than being reported as a successful retry.
            if not found then
                raise;
            end if;

            return reserved;
    end;

    return reserved;
end;
$$;

-- Replacing a function resets its privileges to EXECUTE for PUBLIC, so the lockdown has to be
-- restated. Dropping the old signature also dropped its grants, which is the intended outcome.
revoke all on function public.reserve_storyboard_generation(uuid, uuid, uuid, text, text, text, text, integer)
    from public, anon, authenticated;

grant execute on function public.reserve_storyboard_generation(uuid, uuid, uuid, text, text, text, text, integer)
    to authenticated;
